// DO NOT EDIT — generated by style-dictionary (pnpm tokens:build)
// Source of truth: design/tokens.json. Run `pnpm tokens:build` to regenerate.
import 'package:flutter/material.dart';

/// Design tokens for PinShop TJ. Screen code should reference these, not raw
/// hex. The ThemeData (app_theme.dart) is assembled from them.
abstract final class AppColors {
  // Brand green scale (canonical user accent).
  static const accent = Color(0xFF22C55E);
  static const accentHover = Color(0xFF16A34A);
  static const accentDeep = Color(0xFF15803D);
  static const accentPlate = Color(0xFFDCFCE7);
  static const accentBorder = Color(0xFFBBF7D0);

  // Client surface — cream (never pure #fff/#000).
  static const bg = Color(0xFFFAFAFA);
  static const surface = Color(0xFFFFFFFF);
  static const ink = Color(0xFF1A2B23);
  static const inkMuted = Color(0xFF6B7C74);
  static const inkFaint = Color(0xFF9AA8A0);
  static const line = Color(0xFFECEEF1);

  static const danger = Color(0xFFEF4444);
  static const onAccent = Color(0xFFFFFFFF);

  // Rating (semantic) — filled stars + histogram bars ONLY (Phase 24).
  static const rating = Color(0xFFF59E0B);

  // B2B business-ink surface (header band, MOQ badge, lock CTA).
  static const b2bBand = Color(0xFF10241B);
  // (color/flutter transform already produced the Color(0xFF..) literal above)
}

abstract final class AppRadii {
  static const card = 16.0;
  static const control = 12.0;
  static const image = 16.0;
  static const sheet = 20.0;
  static const pill = 999.0;
}

abstract final class AppSpace {
  static const xs = 4.0;
  static const sm = 8.0;
  static const md = 12.0;
  static const lg = 16.0;
  static const xl = 24.0;
  static const xxl = 32.0;
  static const xxxl = 48.0;
}

abstract final class AppMotion {
  static const tap = Duration(milliseconds: 150);
  static const enter = Duration(milliseconds: 240);
  static const page = Duration(milliseconds: 320);
  static const curve = Curves.easeOutCubic;
  static const curveStrong = Curves.easeOutQuint;
}

abstract final class AppShadows {
  /// Soft layered card shadow (not Material default).
  static List<BoxShadow> get soft => [
        BoxShadow(
          color: const Color(0xFF0F1A14).withValues(alpha: 0.05),
          blurRadius: 16,
          offset: const Offset(0, 6),
        ),
        BoxShadow(
          color: const Color(0xFF0F1A14).withValues(alpha: 0.03),
          blurRadius: 2,
          offset: const Offset(0, 1),
        ),
      ];
}
