// AppLocalizations is generated by flutter gen-l10n from lib/l10n/app_*.arb
// (generate: true in pubspec.yaml + l10n.yaml). Run `flutter pub get` to regenerate.
import 'package:pinshop_tj/l10n/app_localizations.dart';
import 'package:pinshop_tj/l10n/tg_material_localizations.dart';

import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'router/app_router.dart';
import 'theme/app_theme.dart';
import 'features/auth/providers/auth_provider.dart';
import 'core/storage/secure_storage.dart';

/// Entry point.
///
/// Deferred run commands (Flutter SDK required):
///   cd mobile
///   flutter pub get
///   flutter analyze
///   flutter test
///   flutter run --dart-define=API_URL=http://localhost:8080
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  final storage = SecureStorage();
  final initialAuthState = await loadInitialAuthState(storage);

  runApp(
    ProviderScope(
      overrides: [
        secureStorageProvider.overrideWithValue(storage),
        authInitialStateProvider.overrideWithValue(initialAuthState),
      ],
      child: const PinShopApp(),
    ),
  );
}

class PinShopApp extends ConsumerWidget {
  const PinShopApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final router = ref.watch(routerProvider);
    final authState = ref.watch(authProvider);

    // Map locale string to Locale object
    final locale = _localeFromString(authState.locale);

    return MaterialApp.router(
      title: 'ChinaShop TJ',
      theme: getAppTheme(),
      routerConfig: router,
      locale: locale,

      // l10n delegates — AppLocalizations.delegate is generated by flutter gen-l10n.
      localizationsDelegates: const [
        AppLocalizations.delegate,
        // Tajik (tg) has no built-in framework localizations; serve Russian
        // Material/Cupertino strings for tg. Must precede the Global delegates.
        TgMaterialLocalizationsDelegate(),
        TgCupertinoLocalizationsDelegate(),
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      supportedLocales: const [
        Locale('en'),
        Locale('ru'),
        Locale('tg'),
      ],
      debugShowCheckedModeBanner: false,
    );
  }

  Locale _localeFromString(String code) {
    switch (code) {
      case 'ru':
        return const Locale('ru');
      case 'tg':
        return const Locale('tg');
      default:
        return const Locale('en');
    }
  }
}
